php:
  build: .
  container_name: php
  ports:
    - "80:80"
    - "443:443"
  volumes:   
    - ./www:/var/www/html
  links: 
    - db

db: 
  image: mysql:5.7
  container_name: mysql
  volumes: 
    - /var/lib/mysql
  environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=mydb